import { siteSettings } from "./site-settings";
export const sitePages = {
    "hang-moi-ve": {
        page_title: "Hàng mới về | Joolux",
        page_description: "Thương hiệu được các tín đồ thời trang yêu thích",
        banner_title_id: "hangMoiVeId",
        banner_description_id: "hangMoiVeSubtitle",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    blog: {
        page_title: "Blog | Joolux",
        page_description: "Thương hiệu được các tín đồ thời trang yêu thích",
        banner_title_id: "blogId",
        banner_description_id: "blogSubtitle",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    brands: {
        page_title: "Tất cả thương hiệu | Joolux",
        page_description: "Thương hiệu được các tín đồ thời trang yêu thích",
        banner_title_id: "brandsId",
        banner_description_id: "brandsSubtitle",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "tui-xach": {
        page_title: "Túi xách | Joolux",
        page_description: "Một chiếc túi sẽ cho người khác biết nhiều về bạn",
        banner_title_id: "tuiXacTitle",
        banner_description_id: "tuiXachSubtitle",
        banner: "https://joolux.com/img/menu/mega-2.jpg",
    },
    "giay-sneaker": {
        page_title: "Giày & Sneaker | Joolux",
        page_description: "Một đôi giày tốt sẽ giúp bạn đi xa",
        banner_title_id: "giaySneakerTitle",
        banner_description_id: "giaySneakerSubTitle",
        banner: "https://joolux.com/img/menu/mega-3.jpg",
    },
    "dong-ho-cao-cap": {
        page_title: "Đồng hồ | Joolux",
        page_description:
            "Không chỉ cho biết thời gian, đồng hồ còn cho biết bạn là ai",
        banner_title_id: "dongHoTitle",
        banner_description_id: "dongHoSubTitle",
        banner: "https://joolux.com/img/menu/mega-4.jpg",
    },
    "phu-kien": {
        page_title: "Phụ kiện | Joolux",
        page_description:
            "Một phụ kiện dù nhỏ nhưng góp phần hoàn thiện trang phục của bạn",
        banner_title_id: "phuKienTitle",
        banner_description_id: "phuKienSubTitle",
        banner: "https://joolux.com/img/menu/mega-5.jpg",
    },
    "ve-chung-toi": {
        page_title: "Về chúng tôi",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "cam-ket-tu-joolux": {
        page_title: "Cam kết từ Joolux",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "chinh-sach-bao-mat": {
        page_title: "Chính sách bảo mật",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "chinh-sach-bao-hanh-doi-tra": {
        page_title: "Chính sách bảo hành và đổi trả",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "chinh-sach-thanh-toan": {
        page_title: "Chính sách thanh toán",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "chinh-sach-van-chuyen": {
        page_title: "Chính sách vận chuyển",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    "quy-che-hoat-dong": {
        page_title: "Quy chế hoạt động",
        page_description: siteSettings.description,
        banner_title_id: "JooluxOtherPagesTitleId",
        banner_description_id: "JooluxOtherPagesDescriptionId",
        banner: "https://joolux.com/img/menu/mega-1.jpg",
    },
    error: {
        page_title: "Joolux - Trang không tồn tại",
        page_description: "Trang này không tồn tại",
        banner_title_id: "errorsTitle",
        banner_description_id: "errosSubTitle",
    },
};
